feat(monitor): automatically clear data outside the coverage period
RSS3-Network/Node pull request #522
Opened 2024-09-04 09:05 UTC by polebug

## Summary

## Checklist

- [X] The commit message follows [Angular Contributing guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit);
- [ ] Tests for the changes have been added (for bug fixes / features);

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

## Other information

2024-09-05 16:16 UTC, pseudoyu commented on provider/redis/client.go
> +func NewRedisClient(option config.Redis) (*redis.Client, error) {
maybe we can just use goredis instead of using two versions of redis pkg?

2024-09-05 16:26 UTC, pseudoyu commented on config/config.go
> +	CoveragePeriod int             `mapstructure:"coverage_period" validate:"required" default:"3"`
should also add coverage_period config in min/default config file.

and should also notify Explorer to modify the config file gereration logics.

2024-09-05 23:31 UTC, brucexc commented on config/parameter/network.go
```suggestion
It would be better to use chainID for differentiation
```

2024-09-06 03:06 UTC, brucexc commented on internal/node/monitor/server.go
> +				return
```suggestion
Add a log for MaintainCoveragePeriod error to help with troubleshooting
```

2024-09-06 14:33 UTC, pseudoyu approved these changes

2024-09-07 21:09 UTC, brucexc requested changes

2024-09-09 03:01 UTC, polebug commented on provider/redis/client.go
> +	tls, err := buildTLSConfig(option.TLS)
remove go-redis pkg

2024-09-09 04:05 UTC, brucexc approved these changes

2024-09-09 06:56 UTC, merged