fix: `/workers_status` api fetchWorker logics
RSS3-Network/Node pull request #625
Opened 2024-11-01 03:02 UTC by pseudoyu

## Summary

fix `/workers_status` api fetchWorker logics

## Checklist

- [x] The commit message follows [Angular Contributing guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit);
- [x] Tests for the changes have been added (for bug fixes / features);

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2024-11-01 16:52 UTC, brucexc approved these changes

2024-11-04 09:03 UTC, polebug approved these changes

2024-11-05 21:17 UTC, brucexc requested changes

2024-11-06 00:45 UTC, pseudoyu commented on internal/node/component/info/component.go
> +	// Initialize curve registry.
remove.

2024-11-06 00:45 UTC, pseudoyu commented on internal/node/component/info/handler_worker.go
> +		}
resolved.

2024-11-06 02:00 UTC, brucexc approved these changes

2024-11-06 02:01 UTC, merged